// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from message.proto</summary>
public static partial class MessageReflection {

  #region Descriptor
  /// <summary>File descriptor for message.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1tZXNzYWdlLnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnBy",
          "b3RvIrkCChNJbmZyYXN0cnVjdHVyZUV2ZW50EgoKAmlkGAEgASgJEisKCWV2",
          "bnRfdHlwZRgCIAEoDjIYLkluZnJhc3RydWN0dXJlRXZlbnRUeXBlEhQKDG9w",
          "ZXJhdGlvbl9pZBgDIAEoCRIRCglyb3V0ZXJfaWQYBCABKAkSEQoJcG9ydGFs",
          "X2lkGAUgASgJEhAKCHJlbGF5X2lkGAYgASgJEg8KB2NvcmVfaWQYByABKAkS",
          "FQoNYWdncmVnYXRvcl9pZBgIIAEoCRItCgl0aW1lc3RhbXAYCSABKAsyGi5n",
          "b29nbGUucHJvdG9idWYuVGltZXN0YW1wEiMKCGNvbW1hbmRzGAogAygLMhEu",
          "RG9tYWluQ29tbWFuZER0bxIfCgZldmVudHMYCyADKAsyDy5Eb21haW5FdmVu",
          "dER0byKZAQoORG9tYWluRXZlbnREdG8SCgoCaWQYASABKAkSFAoMYWdncmVn",
          "YXRlX2lkGAIgASgJEhEKCXNvdXJjZV9pZBgDIAEoCRISCgpjb21tYW5kX2lk",
          "GAQgASgJEhAKCGNvbmZsaWN0GAUgASgIEiwKCHRpbWVzcGFuGAYgASgLMhou",
          "Z29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJyChBEb21haW5Db21tYW5kRHRv",
          "EgoKAmlkGAEgASgJEhQKDGFnZ3JlZ2F0ZV9pZBgCIAEoCRIOCgZzZW5kZXIY",
          "AyABKAkSLAoIdGltZXNwYW4YBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGlt",
          "ZXN0YW1wKs4BChdJbmZyYXN0cnVjdHVyZUV2ZW50VHlwZRIVChFOb3RTcGVj",
          "aWZpZWRFdmVudBAAEiYKIkFwcGxpY2F0aW9uT3BlcmF0aW9uSW5pdGlhdGVk",
          "RXZlbnQQARIfChtSZWxheUV2ZW50c1RyYW5zbWlpdGVkRXZlbnQQAhIZChVF",
          "dmVudHNBZ2dyZWdhdGVkRXZlbnQQAxIcChhUcmFuc2FjdGlvbkV4ZWN1dGVk",
          "RXZlbnQQBBIaChZUcmFuc2FjdGlvblJvdXRlZEV2ZW50EAViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::InfrastructureEventType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::InfrastructureEvent), global::InfrastructureEvent.Parser, new[]{ "Id", "EvntType", "OperationId", "RouterId", "PortalId", "RelayId", "CoreId", "AggregatorId", "Timestamp", "Commands", "Events" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DomainEventDto), global::DomainEventDto.Parser, new[]{ "Id", "AggregateId", "SourceId", "CommandId", "Conflict", "Timespan" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DomainCommandDto), global::DomainCommandDto.Parser, new[]{ "Id", "AggregateId", "Sender", "Timespan" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum InfrastructureEventType {
  [pbr::OriginalName("NotSpecifiedEvent")] NotSpecifiedEvent = 0,
  [pbr::OriginalName("ApplicationOperationInitiatedEvent")] ApplicationOperationInitiatedEvent = 1,
  [pbr::OriginalName("RelayEventsTransmiitedEvent")] RelayEventsTransmiitedEvent = 2,
  [pbr::OriginalName("EventsAggregatedEvent")] EventsAggregatedEvent = 3,
  [pbr::OriginalName("TransactionExecutedEvent")] TransactionExecutedEvent = 4,
  [pbr::OriginalName("TransactionRoutedEvent")] TransactionRoutedEvent = 5,
}

#endregion

#region Messages
public sealed partial class InfrastructureEvent : pb::IMessage<InfrastructureEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<InfrastructureEvent> _parser = new pb::MessageParser<InfrastructureEvent>(() => new InfrastructureEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<InfrastructureEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InfrastructureEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InfrastructureEvent(InfrastructureEvent other) : this() {
    id_ = other.id_;
    evntType_ = other.evntType_;
    operationId_ = other.operationId_;
    routerId_ = other.routerId_;
    portalId_ = other.portalId_;
    relayId_ = other.relayId_;
    coreId_ = other.coreId_;
    aggregatorId_ = other.aggregatorId_;
    timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
    commands_ = other.commands_.Clone();
    events_ = other.events_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InfrastructureEvent Clone() {
    return new InfrastructureEvent(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "evnt_type" field.</summary>
  public const int EvntTypeFieldNumber = 2;
  private global::InfrastructureEventType evntType_ = global::InfrastructureEventType.NotSpecifiedEvent;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::InfrastructureEventType EvntType {
    get { return evntType_; }
    set {
      evntType_ = value;
    }
  }

  /// <summary>Field number for the "operation_id" field.</summary>
  public const int OperationIdFieldNumber = 3;
  private string operationId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string OperationId {
    get { return operationId_; }
    set {
      operationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "router_id" field.</summary>
  public const int RouterIdFieldNumber = 4;
  private string routerId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string RouterId {
    get { return routerId_; }
    set {
      routerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "portal_id" field.</summary>
  public const int PortalIdFieldNumber = 5;
  private string portalId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PortalId {
    get { return portalId_; }
    set {
      portalId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "relay_id" field.</summary>
  public const int RelayIdFieldNumber = 6;
  private string relayId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string RelayId {
    get { return relayId_; }
    set {
      relayId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "core_id" field.</summary>
  public const int CoreIdFieldNumber = 7;
  private string coreId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CoreId {
    get { return coreId_; }
    set {
      coreId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "aggregator_id" field.</summary>
  public const int AggregatorIdFieldNumber = 8;
  private string aggregatorId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AggregatorId {
    get { return aggregatorId_; }
    set {
      aggregatorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 9;
  private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = value;
    }
  }

  /// <summary>Field number for the "commands" field.</summary>
  public const int CommandsFieldNumber = 10;
  private static readonly pb::FieldCodec<global::DomainCommandDto> _repeated_commands_codec
      = pb::FieldCodec.ForMessage(82, global::DomainCommandDto.Parser);
  private readonly pbc::RepeatedField<global::DomainCommandDto> commands_ = new pbc::RepeatedField<global::DomainCommandDto>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::DomainCommandDto> Commands {
    get { return commands_; }
  }

  /// <summary>Field number for the "events" field.</summary>
  public const int EventsFieldNumber = 11;
  private static readonly pb::FieldCodec<global::DomainEventDto> _repeated_events_codec
      = pb::FieldCodec.ForMessage(90, global::DomainEventDto.Parser);
  private readonly pbc::RepeatedField<global::DomainEventDto> events_ = new pbc::RepeatedField<global::DomainEventDto>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::DomainEventDto> Events {
    get { return events_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as InfrastructureEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(InfrastructureEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (EvntType != other.EvntType) return false;
    if (OperationId != other.OperationId) return false;
    if (RouterId != other.RouterId) return false;
    if (PortalId != other.PortalId) return false;
    if (RelayId != other.RelayId) return false;
    if (CoreId != other.CoreId) return false;
    if (AggregatorId != other.AggregatorId) return false;
    if (!object.Equals(Timestamp, other.Timestamp)) return false;
    if(!commands_.Equals(other.commands_)) return false;
    if(!events_.Equals(other.events_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (EvntType != global::InfrastructureEventType.NotSpecifiedEvent) hash ^= EvntType.GetHashCode();
    if (OperationId.Length != 0) hash ^= OperationId.GetHashCode();
    if (RouterId.Length != 0) hash ^= RouterId.GetHashCode();
    if (PortalId.Length != 0) hash ^= PortalId.GetHashCode();
    if (RelayId.Length != 0) hash ^= RelayId.GetHashCode();
    if (CoreId.Length != 0) hash ^= CoreId.GetHashCode();
    if (AggregatorId.Length != 0) hash ^= AggregatorId.GetHashCode();
    if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
    hash ^= commands_.GetHashCode();
    hash ^= events_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (EvntType != global::InfrastructureEventType.NotSpecifiedEvent) {
      output.WriteRawTag(16);
      output.WriteEnum((int) EvntType);
    }
    if (OperationId.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(OperationId);
    }
    if (RouterId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(RouterId);
    }
    if (PortalId.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(PortalId);
    }
    if (RelayId.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(RelayId);
    }
    if (CoreId.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(CoreId);
    }
    if (AggregatorId.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(AggregatorId);
    }
    if (timestamp_ != null) {
      output.WriteRawTag(74);
      output.WriteMessage(Timestamp);
    }
    commands_.WriteTo(output, _repeated_commands_codec);
    events_.WriteTo(output, _repeated_events_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (EvntType != global::InfrastructureEventType.NotSpecifiedEvent) {
      output.WriteRawTag(16);
      output.WriteEnum((int) EvntType);
    }
    if (OperationId.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(OperationId);
    }
    if (RouterId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(RouterId);
    }
    if (PortalId.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(PortalId);
    }
    if (RelayId.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(RelayId);
    }
    if (CoreId.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(CoreId);
    }
    if (AggregatorId.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(AggregatorId);
    }
    if (timestamp_ != null) {
      output.WriteRawTag(74);
      output.WriteMessage(Timestamp);
    }
    commands_.WriteTo(ref output, _repeated_commands_codec);
    events_.WriteTo(ref output, _repeated_events_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (EvntType != global::InfrastructureEventType.NotSpecifiedEvent) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EvntType);
    }
    if (OperationId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(OperationId);
    }
    if (RouterId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RouterId);
    }
    if (PortalId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PortalId);
    }
    if (RelayId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RelayId);
    }
    if (CoreId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CoreId);
    }
    if (AggregatorId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AggregatorId);
    }
    if (timestamp_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
    }
    size += commands_.CalculateSize(_repeated_commands_codec);
    size += events_.CalculateSize(_repeated_events_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(InfrastructureEvent other) {
    if (other == null) {
      return;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.EvntType != global::InfrastructureEventType.NotSpecifiedEvent) {
      EvntType = other.EvntType;
    }
    if (other.OperationId.Length != 0) {
      OperationId = other.OperationId;
    }
    if (other.RouterId.Length != 0) {
      RouterId = other.RouterId;
    }
    if (other.PortalId.Length != 0) {
      PortalId = other.PortalId;
    }
    if (other.RelayId.Length != 0) {
      RelayId = other.RelayId;
    }
    if (other.CoreId.Length != 0) {
      CoreId = other.CoreId;
    }
    if (other.AggregatorId.Length != 0) {
      AggregatorId = other.AggregatorId;
    }
    if (other.timestamp_ != null) {
      if (timestamp_ == null) {
        Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      Timestamp.MergeFrom(other.Timestamp);
    }
    commands_.Add(other.commands_);
    events_.Add(other.events_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 16: {
          EvntType = (global::InfrastructureEventType) input.ReadEnum();
          break;
        }
        case 26: {
          OperationId = input.ReadString();
          break;
        }
        case 34: {
          RouterId = input.ReadString();
          break;
        }
        case 42: {
          PortalId = input.ReadString();
          break;
        }
        case 50: {
          RelayId = input.ReadString();
          break;
        }
        case 58: {
          CoreId = input.ReadString();
          break;
        }
        case 66: {
          AggregatorId = input.ReadString();
          break;
        }
        case 74: {
          if (timestamp_ == null) {
            Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(Timestamp);
          break;
        }
        case 82: {
          commands_.AddEntriesFrom(input, _repeated_commands_codec);
          break;
        }
        case 90: {
          events_.AddEntriesFrom(input, _repeated_events_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 16: {
          EvntType = (global::InfrastructureEventType) input.ReadEnum();
          break;
        }
        case 26: {
          OperationId = input.ReadString();
          break;
        }
        case 34: {
          RouterId = input.ReadString();
          break;
        }
        case 42: {
          PortalId = input.ReadString();
          break;
        }
        case 50: {
          RelayId = input.ReadString();
          break;
        }
        case 58: {
          CoreId = input.ReadString();
          break;
        }
        case 66: {
          AggregatorId = input.ReadString();
          break;
        }
        case 74: {
          if (timestamp_ == null) {
            Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(Timestamp);
          break;
        }
        case 82: {
          commands_.AddEntriesFrom(ref input, _repeated_commands_codec);
          break;
        }
        case 90: {
          events_.AddEntriesFrom(ref input, _repeated_events_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class DomainEventDto : pb::IMessage<DomainEventDto>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DomainEventDto> _parser = new pb::MessageParser<DomainEventDto>(() => new DomainEventDto());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DomainEventDto> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DomainEventDto() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DomainEventDto(DomainEventDto other) : this() {
    id_ = other.id_;
    aggregateId_ = other.aggregateId_;
    sourceId_ = other.sourceId_;
    commandId_ = other.commandId_;
    conflict_ = other.conflict_;
    timespan_ = other.timespan_ != null ? other.timespan_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DomainEventDto Clone() {
    return new DomainEventDto(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "aggregate_id" field.</summary>
  public const int AggregateIdFieldNumber = 2;
  private string aggregateId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AggregateId {
    get { return aggregateId_; }
    set {
      aggregateId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "source_id" field.</summary>
  public const int SourceIdFieldNumber = 3;
  private string sourceId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SourceId {
    get { return sourceId_; }
    set {
      sourceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "command_id" field.</summary>
  public const int CommandIdFieldNumber = 4;
  private string commandId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CommandId {
    get { return commandId_; }
    set {
      commandId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "conflict" field.</summary>
  public const int ConflictFieldNumber = 5;
  private bool conflict_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Conflict {
    get { return conflict_; }
    set {
      conflict_ = value;
    }
  }

  /// <summary>Field number for the "timespan" field.</summary>
  public const int TimespanFieldNumber = 6;
  private global::Google.Protobuf.WellKnownTypes.Timestamp timespan_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp Timespan {
    get { return timespan_; }
    set {
      timespan_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DomainEventDto);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DomainEventDto other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (AggregateId != other.AggregateId) return false;
    if (SourceId != other.SourceId) return false;
    if (CommandId != other.CommandId) return false;
    if (Conflict != other.Conflict) return false;
    if (!object.Equals(Timespan, other.Timespan)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (AggregateId.Length != 0) hash ^= AggregateId.GetHashCode();
    if (SourceId.Length != 0) hash ^= SourceId.GetHashCode();
    if (CommandId.Length != 0) hash ^= CommandId.GetHashCode();
    if (Conflict != false) hash ^= Conflict.GetHashCode();
    if (timespan_ != null) hash ^= Timespan.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (AggregateId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(AggregateId);
    }
    if (SourceId.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(SourceId);
    }
    if (CommandId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(CommandId);
    }
    if (Conflict != false) {
      output.WriteRawTag(40);
      output.WriteBool(Conflict);
    }
    if (timespan_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(Timespan);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (AggregateId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(AggregateId);
    }
    if (SourceId.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(SourceId);
    }
    if (CommandId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(CommandId);
    }
    if (Conflict != false) {
      output.WriteRawTag(40);
      output.WriteBool(Conflict);
    }
    if (timespan_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(Timespan);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (AggregateId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AggregateId);
    }
    if (SourceId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SourceId);
    }
    if (CommandId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CommandId);
    }
    if (Conflict != false) {
      size += 1 + 1;
    }
    if (timespan_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timespan);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DomainEventDto other) {
    if (other == null) {
      return;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.AggregateId.Length != 0) {
      AggregateId = other.AggregateId;
    }
    if (other.SourceId.Length != 0) {
      SourceId = other.SourceId;
    }
    if (other.CommandId.Length != 0) {
      CommandId = other.CommandId;
    }
    if (other.Conflict != false) {
      Conflict = other.Conflict;
    }
    if (other.timespan_ != null) {
      if (timespan_ == null) {
        Timespan = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      Timespan.MergeFrom(other.Timespan);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          AggregateId = input.ReadString();
          break;
        }
        case 26: {
          SourceId = input.ReadString();
          break;
        }
        case 34: {
          CommandId = input.ReadString();
          break;
        }
        case 40: {
          Conflict = input.ReadBool();
          break;
        }
        case 50: {
          if (timespan_ == null) {
            Timespan = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(Timespan);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          AggregateId = input.ReadString();
          break;
        }
        case 26: {
          SourceId = input.ReadString();
          break;
        }
        case 34: {
          CommandId = input.ReadString();
          break;
        }
        case 40: {
          Conflict = input.ReadBool();
          break;
        }
        case 50: {
          if (timespan_ == null) {
            Timespan = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(Timespan);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class DomainCommandDto : pb::IMessage<DomainCommandDto>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DomainCommandDto> _parser = new pb::MessageParser<DomainCommandDto>(() => new DomainCommandDto());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DomainCommandDto> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DomainCommandDto() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DomainCommandDto(DomainCommandDto other) : this() {
    id_ = other.id_;
    aggregateId_ = other.aggregateId_;
    sender_ = other.sender_;
    timespan_ = other.timespan_ != null ? other.timespan_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DomainCommandDto Clone() {
    return new DomainCommandDto(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "aggregate_id" field.</summary>
  public const int AggregateIdFieldNumber = 2;
  private string aggregateId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AggregateId {
    get { return aggregateId_; }
    set {
      aggregateId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "sender" field.</summary>
  public const int SenderFieldNumber = 3;
  private string sender_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Sender {
    get { return sender_; }
    set {
      sender_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "timespan" field.</summary>
  public const int TimespanFieldNumber = 4;
  private global::Google.Protobuf.WellKnownTypes.Timestamp timespan_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp Timespan {
    get { return timespan_; }
    set {
      timespan_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DomainCommandDto);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DomainCommandDto other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (AggregateId != other.AggregateId) return false;
    if (Sender != other.Sender) return false;
    if (!object.Equals(Timespan, other.Timespan)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (AggregateId.Length != 0) hash ^= AggregateId.GetHashCode();
    if (Sender.Length != 0) hash ^= Sender.GetHashCode();
    if (timespan_ != null) hash ^= Timespan.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (AggregateId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(AggregateId);
    }
    if (Sender.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Sender);
    }
    if (timespan_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Timespan);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (AggregateId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(AggregateId);
    }
    if (Sender.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Sender);
    }
    if (timespan_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Timespan);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (AggregateId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AggregateId);
    }
    if (Sender.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Sender);
    }
    if (timespan_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timespan);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DomainCommandDto other) {
    if (other == null) {
      return;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.AggregateId.Length != 0) {
      AggregateId = other.AggregateId;
    }
    if (other.Sender.Length != 0) {
      Sender = other.Sender;
    }
    if (other.timespan_ != null) {
      if (timespan_ == null) {
        Timespan = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      Timespan.MergeFrom(other.Timespan);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          AggregateId = input.ReadString();
          break;
        }
        case 26: {
          Sender = input.ReadString();
          break;
        }
        case 34: {
          if (timespan_ == null) {
            Timespan = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(Timespan);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          AggregateId = input.ReadString();
          break;
        }
        case 26: {
          Sender = input.ReadString();
          break;
        }
        case 34: {
          if (timespan_ == null) {
            Timespan = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(Timespan);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
